### ISSUE TITLE
Error: Format prefix not allowed

### ISSUE THREAD

**Issue by oharkins** [b1f6c1c4/draw.io-export#20]
I can not get this to run.

`drawio diagram.drawio -o diagram.png`

`npm -v 9.4.0`
`node -v v19.6.0`

Error: Format prefix not allowed
    at module.exports (/usr/local/lib/node_modules/draw.io-export/export.js:187:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Error: Format prefix not allowed
    at module.exports (/usr/local/lib/node_modules/draw.io-export/export.js:187:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by b1f6c1c4** [comment]
Can you show me the result of `drawio --version`? I cannot reproduce the result on `drawio 0.2.0` (newest version).

BTW, is `drawio diagram.drawio -o diagram.png` the *complete* command line arguments you are using `drawio`?

**Comment by oharkins** [comment]
drawio --version 0.2.0

`cfn-dia draw.io -t template.yaml -c -o diagram.drawio`

**Comment by oharkins** [comment]
[diagram.txt](https://github.com/b1f6c1c4/draw.io-export/files/10886418/diagram.tx
![Screen Shot 2023-03-03 at 2 56 34 PM](https://user-images.githubusercontent.com/5509758/222837835-8b81808a-9581-4113-baae-4ad9bc9840a1.png)
