### ISSUE TITLE
issue running draw.io-export when running on new version of drawio version < 20.8.16

### ISSUE THREAD

**Issue by cuietviper** [b1f6c1c4/draw.io-export#21]
A great and simple tool, but I am facing an issue running draw.io-export when running on the new version of drawio < 20.8.16. I have attached the error logs below. It was running fine before but failed when we try to generate pdf with files that were created using a newer version of drawio.  If you need any additional logs, let me know. @b1f6c1c4 

Error: Evaluation failed: TypeError: doc.documentElement.firstChild.getAttribute is not a function
    at pptr://__puppeteer_evaluation_script__:1:39
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\prabhu\AppData\Roaming\npm\node_modules\draw.io-export\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Users\prabhu\AppData\Roaming\npm\node_modules\draw.io-export\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:117:16)
    at async module.exports (C:\Users\prabhu\AppData\Roaming\npm\node_modules\draw.io-export\export.js:182:24)
Error: Evaluation failed: TypeError: doc.documentElement.firstChild.getAttribute is not a function
    at pptr://__puppeteer_evaluation_script__:1:39
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\prabhu\AppData\Roaming\npm\node_modules\draw.io-export\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Users\prabhu\AppData\Roaming\npm\node_modules\draw.io-export\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:117:16)
    at async module.exports (C:\Users\prabhu\AppData\Roaming\npm\node_modules\draw.io-export\export.js:182:24)

**Comment by cuietviper** [comment]
thanks for the update. i updated the draw.io-export to 0.3 (i doubled checked and confirm that i am using 0.30) but still i am getting the following 

Error: Evaluation failed: TypeError: doc.documentElement.firstChild.getAttribute is not a function
    at pptr://__puppeteer_evaluation_script__:1:39
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\prabhu\AppData\Roaming\npm\node_modules\draw.io-export\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Users\prabhu\AppData\Roaming\npm\node_modules\draw.io-export\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:117:16)
    at async module.exports (C:\Users\prabhu\AppData\Roaming\npm\node_modules\draw.io-export\export.js:186:24)
Error: Evaluation failed: TypeError: doc.documentElement.firstChild.getAttribute is not a function
    at pptr://__puppeteer_evaluation_script__:1:39
    at ExecutionContext._ExecutionContext_evaluate (C:\Users\prabhu\AppData\Roaming\npm\node_modules\draw.io-export\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:286:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ExecutionContext.evaluate (C:\Users\prabhu\AppData\Roaming\npm\node_modules\draw.io-export\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:117:16)
    at async module.exports (C:\Users\prabhu\AppData\Roaming\npm\node_modules\draw.io-export\export.js:186:24)
Generated ASSA_overview.pdf in _image folder from ASSA_overview.drawio


one addition pointer: npm WARN deprecated puppeteer@14.4.1: < 19.4.0 is no longer supported

**Comment by b1f6c1c4** [comment]
You shall double check the content of `C:\Users\prabhu\AppData\Roaming\npm\node_modules\draw.io-export\export.js`, L186. @cuietviper
